In [1]:
import pandas as pd
import numpy as np
import math

In [8]:
# Get Volume of passenger transport relative to GDP data for Euro area from TIL6022-Project(https://github.com/JorisVoogt/TIL6022-Project)
pg_GDP_url = 'https://github.com/JorisVoogt/TIL6022-Project/tree/data/data/pg_GDP.csv'
df_pg_GDP = pd.read_csv(pg_GDP_url,error_bad_lines=False)

#Get Rail transport of passengers
df_rail_pg = pd.read_csv('data/pg_GDP.csv')

# Get Road transport (Buses and coaches) of passengers
df_road_pg = pd.read_csv('data/road_pg')

C:\Users\猫小鱼\AppData\Local\Temp\ipykernel_34872\484327864.py:5: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df_pg_GDP = pd.read_csv(pg_GDP_url,error_bad_lines=False)
Skipping line 33: expected 1 fields, saw 6
Skipping line 110: expected 1 fields, saw 3
Skipping line 143: expected 1 fields, saw 2
Skipping line 222: expected 1 fields, saw 3
Skipping line 231: expected 1 fields, saw 6
Skipping line 263: expected 1 fields, saw 4
Skipping line 276: expected 1 fields, saw 4
Skipping line 289: expected 1 fields, saw 4
Skipping line 302: expected 1 fields, saw 4
Skipping line 315: expected 1 fields, saw 4
Skipping line 328: expected 1 fields, saw 4
Skipping line 341: expected 1 fields, saw 4
Skipping line 354: expected 1 fields, saw 4
Skipping line 372: expected 1 fields, saw 4
Skipping line 379: expected 1 fields, saw 4
Skipping line 388: expected 1 fields, saw 4
Skipping line 397: expected 1 fields, saw 4
Skipping line 423: expected 1 fields, saw 4
Skipping line 430: expected 1 fields, saw 4
Skipping line 437: expected 1 fields, saw 4
Skipping line 444: expected 1 fields, saw 4
Skipping line 458: expected 1 fields, saw 4
Skipping line 465: expected 1 fields, saw 4
Skipping line 474: expected 1 fields, saw 4
Skipping line 488: expected 1 fields, saw 4
Skipping line 497: expected 1 fields, saw 8
Skipping line 498: expected 1 fields, saw 3
Skipping line 506: expected 1 fields, saw 4
Skipping line 513: expected 1 fields, saw 4
Skipping line 538: expected 1 fields, saw 4
Skipping line 553: expected 1 fields, saw 4
Skipping line 569: expected 1 fields, saw 4
Skipping line 576: expected 1 fields, saw 4
Skipping line 583: expected 1 fields, saw 4
Skipping line 596: expected 1 fields, saw 3
Skipping line 616: expected 1 fields, saw 2
Skipping line 637: expected 1 fields, saw 5
Skipping line 815: expected 1 fields, saw 2
Skipping line 886: expected 1 fields, saw 2
Skipping line 909: expected 1 fields, saw 6
Skipping line 910: expected 1 fields, saw 3
Skipping line 917: expected 1 fields, saw 6
Skipping line 918: expected 1 fields, saw 3
Skipping line 1041: expected 1 fields, saw 6
Skipping line 1048: expected 1 fields, saw 6
Skipping line 1057: expected 1 fields, saw 6
Skipping line 1081: expected 1 fields, saw 4
Skipping line 1093: expected 1 fields, saw 4
Skipping line 1105: expected 1 fields, saw 4
Skipping line 1117: expected 1 fields, saw 4
Skipping line 1129: expected 1 fields, saw 4
Skipping line 1141: expected 1 fields, saw 4
Skipping line 1152: expected 1 fields, saw 4
Skipping line 1235: expected 1 fields, saw 1581
Skipping line 1262: expected 1 fields, saw 2
Skipping line 1270: expected 1 fields, saw 3
Skipping line 1271: expected 1 fields, saw 3
Skipping line 1272: expected 1 fields, saw 3
Skipping line 1273: expected 1 fields, saw 3
Skipping line 1274: expected 1 fields, saw 3
Skipping line 1275: expected 1 fields, saw 3
Skipping line 1276: expected 1 fields, saw 3
Skipping line 1277: expected 1 fields, saw 3
Skipping line 1278: expected 1 fields, saw 3
Skipping line 1279: expected 1 fields, saw 3
Skipping line 1280: expected 1 fields, saw 3

FileNotFoundError: [Errno 2] No such file or directory: 'data/pg_GDP.csv'

In [10]:
# Import Volume of passenger transport relative to GDP: Read the csv file as a dataframe
file_path_pg_GDP = r'C:\Users\猫小鱼\Desktop\TIL\Programming\final project\data\pg_GDP.csv'
df_pg_GDP = pd.read_csv(file_path_pg_GDP)

# Rename columns and rows
df_pg_GDP.columns = df_pg_GDP.iloc[6].tolist()
df_pg_GDP = df_pg_GDP.rename(columns={df_pg_GDP.columns[0]: 'GEO'})

# Clean the data by dropping columns of the dataframe that will not be used
# These rows are used to indicate the data, and columns are used to explain the accuracy of the data
df_pg_GDP = df_pg_GDP.iloc[8:48]
columns_to_remove = [2,4,6,8,10,12,14,16,18,20,22,24]
df_pg_GDP = df_pg_GDP.drop(df_pg_GDP.columns[columns_to_remove], axis=1 )
columns_to_remove = [7]
df_pg_GDP = df_pg_GDP.drop(df_pg_GDP.columns[columns_to_remove], axis=1 )


# Delete the rows without data and use Euro area or country as the row name
df_pg_GDP = df_pg_GDP.set_index('GEO')
df_pg_GDP = df_pg_GDP[~(df_pg_GDP == ':').all(axis=1)]
df_pg_GDP

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
GEO,,,,,,,,,,,,
European Union - 27 countries (from 2020),103.7,102.2,100.9,100.8,100.1,100,100,98.3,96.6,95.4,79.2,80.2
Belgium,114.1,110.5,114,111.5,103.7,100,97.4,96.6,95.5,93.8,80.9,79.9
Bulgaria,91.5,91.2,91.9,94.4,99.1,100,95.9,93.9,89.7,88.7,75.4,72.3
Czechia,101.2,100,99.6,100.7,103.1,100,100.7,99.2,100.9,101.5,83.8,99.2
Denmark,98.7,99.5,98.7,97.7,98.1,100,99.8,98.6,97.2,98.2,88.4,85.9
Germany,101.4,101,101.1,100.9,100.2,100,100,94.6,93.8,91.1,79.9,76.1
Estonia,95.1,90.6,91.9,93.9,95.9,100,104.2,99.8,97.8,100.2,79.1,77.7
Ireland,128.7,126,123.4,125.2,114.3,100,103.8,98.8,93,90.5,70.1,65.7
Greece,82.6,90.6,96.3,98,98.4,100,101.6,101.7,101.3,100.9,91.6,90.3
Spain,106.3,106.6,105.9,105.8,99.4,100,100.6,94.4,94.8,93.6,77.5,79.7
France,108.7,107.1,106.6,99.6,99.8,100,100.2,99,96.7,94.6,79.2,85.8
Croatia,99.2,96.5,100.9,101.7,102.2,100,96.9,94.5,89.3,86.1,71.1,72.1
Italy,99.4,94.7,87.3,94.4,96.5,100,102,105.3,102,102.9,71.9,74.1
Cyprus,86.9,87.2,91.1,96.8,100.4,100,97.9,94.2,92.4,90.1,75.5,76.3
Latvia,111.3,102.7,96.5,95.8,99,100,99.3,102,99.9,98.9,91.1,78.7
Lithuania,153.4,134.2,146,138.1,101.1,100,100.7,115.5,107.5,106.9,93.5,94.9
Luxembourg,98.1,98.8,99.4,98.3,98.8,100,97.6,98.5,99.4,99.6,84.6,86.3
Hungary,108.1,105.7,107.3,104.3,101.3,100,103.1,103.5,100.7,99.3,91.9,89.8
Malta,115.5,115.2,111,106.9,104.6,100,99.8,91,87.3,83.8,76.1,72.9
Netherlands,106.9,105.9,106.8,108,106.8,100,99,95,97,97,68.4,72.4
Austria,97,96,96.1,97.4,99,100,100.8,100.2,90.7,87.5,78.6,80
Poland,112.5,110.4,104.9,104.5,102.4,100,101.8,99.9,96.1,94.4,84.9,83.3
Portugal,95.9,95.7,98.3,98.7,99.3,100,104.4,103.8,104.7,104.8,95.3,97.9
Romania,96.3,91,92,94.8,97.1,100,102.9,97.5,96.8,99.1,88.2,91.2
Slovenia,99.9,98.6,100.5,101.5,100.5,100,98.5,96.1,93.3,91.4,77.5,77.5
Slovakia,107.6,105.3,103.6,103.4,101.8,100,100.5,99.2,97.1,95.4,78.2,77.3
Finland,98.2,96.6,97.9,98.6,99.2,100,86.3,95.7,94.9,94,89.2,85
Sweden,98.5,104.4,104.7,103.5,102.7,100,84.8,84.3,83.5,82.2,74.9,70
Iceland,101.5,96,96.1,94.6,97.8,100,109,114.6,113.2,109.2,101.1,109.6
Norway,100.4,100.9,98.1,98.4,99.5,100,99.6,98.8,99,98.7,89.3,89.3
Switzerland,115.3,103.6,102.9,101.9,100.7,100,99.8,99.6,97.1,97.5,86,86.7
United Kingdom,108.4,107.1,106.1,102.9,102,100,99.4,103.6,103.8,104.3,:,:
Montenegro,108.8,101,105.8,104.7,101.8,100,106.7,103.7,104.5,105.2,99.9,97.9
North Macedonia,75.1,83,77.7,96.3,102.6,100,96.2,95,96.9,93,103.8,110.3
Serbia,110.8,94.9,96.8,96,98.4,100,98.2,97.3,95.5,93.5,80.5,81.8
Türkiye,110.7,106.3,107.7,102.4,100.7,100,99.9,94.4,99.1,102.9,85,82.8

In [11]:
# Import Rail transport of passengers: Read the csv file as a dataframe
file_path_rail_pg = r'C:\Users\猫小鱼\Desktop\TIL\Programming\final project\data\rail_pg.csv'
df_rail_pg = pd.read_csv(file_path_rail_pg)

# Rename columns and rows
df_rail_pg.columns = df_rail_pg.iloc[7].tolist()
df_rail_pg = df_rail_pg.rename(columns={df_rail_pg.columns[0]: 'GEO'})

# Clean the data by dropping columns of the dataframe that will not be used
# These rows are used to indicate the data, and columns are used to explain the accuracy of the data
df_rail_pg = df_rail_pg.iloc[9:49]
columns_to_remove = [2,4,6,8,10,12,14,16,18,20,22,24]
df_rail_pg = df_rail_pg.drop( df_rail_pg.columns[columns_to_remove], axis=1 )

# Delete the rows without data and use European region or country as the row name
df_rail_pg = df_rail_pg.set_index('GEO')
df_rail_pg = df_rail_pg[~(df_rail_pg == ':').all(axis=1)]

df_rail_pg

,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
GEO,,,,,,,,,,,,
European Union - 27 countries (from 2020),:,:,:,:,"375,713","384,335","394,142","400,427","413,923","223,668","260,715",:
Belgium,"10,498",:,:,:,:,:,:,:,:,:,:,:
Bulgaria,"2,059","1,870","1,821","1,698","1,549","1,455","1,434","1,476","1,520","1,118","1,203","1,600"
Czechia,:,"7,196","7,512","7,644","8,125","8,738","9,403","10,220","10,856","6,623","6,752","9,394"
Denmark,"6,395","6,534","6,566","6,513","6,507","6,332","6,280","6,182","6,174","3,940","4,181",:
Germany,"89,316","93,918","89,450","90,978","91,050","95,465","95,529","98,161","100,252","57,787","57,518",:
Estonia,243,235,223,280,286,316,366,417,392,263,290,382
Ireland,"1,638","1,578","1,569","1,728","1,918","1,991","2,122","2,281","2,399",834,870,"1,748"
Greece,958,832,"1,056","1,072","1,263","1,192","1,112","1,104","1,252",640,653,"1,117"
Spain,"22,645","22,170","23,660","24,915","26,018","26,532","27,374","28,317","28,703","11,987","17,002","27,489"
France,"91,298","91,205","90,485","89,499","91,377","91,832","95,024","91,818","96,540","56,606","75,854","102,814"
Croatia,"1,457","1,080",935,917,941,827,736,747,724,448,538,812
Italy,"45,944","45,753","47,707","48,881","51,121","51,716","52,778","55,037","56,160","22,064","27,444",:
Latvia,733,717,721,644,590,584,596,624,643,413,361,541
Lithuania,269,278,278,270,262,280,315,354,359,237,287,382
Luxembourg,349,373,394,366,418,417,438,443,463,268,304,389
Hungary,"7,763","7,769","7,806","7,710",:,:,:,:,:,:,:,:
Austria,"10,172","10,606","11,188","11,345","11,433","12,021","12,077","12,681","12,761","6,964","8,054","12,371"
Poland,"17,633","17,110","16,453","15,479","17,024","18,753","20,120","20,849",:,:,:,"23,646"
Portugal,"4,237","3,803","3,649","3,852","3,957","4,266","4,516","4,570","5,055","2,563","2,912","4,419"
Romania,"5,044","4,518","4,352","4,971","4,910","4,731","5,556","5,426","5,735","3,609","4,104","5,616"
Slovenia,689,659,679,620,628,611,570,568,572,338,504,645
Slovakia,"2,431","2,459","2,485","2,583","3,411","3,484","3,754","3,792","3,957","2,133","1,969","3,168"
Finland,"3,882","4,035","4,053","3,874","4,114","3,868","4,271","4,535","4,924","2,820","2,903","12,556"
Sweden,"11,379","11,792","11,842","12,121","12,741","12,800","13,331","13,547","14,617","8,129","8,027",:
Norway,"3,076","3,092","3,260","3,440","3,555","3,695","3,584","3,722","3,715","1,801","1,780",:
Switzerland,"18,320","18,115","18,277","18,801","19,089","19,573","19,586","19,245","20,315","12,419","13,321",:
United Kingdom,"58,462","60,783","61,950","64,711","66,594","68,010","68,912","69,706","71,823",:,:,:
North Macedonia,145,99,80,80,177,83,59,63,62,25,25,:
Türkiye,"5,882","4,598","3,775","4,393","4,828","4,325","4,566","5,560","11,068","6,094","8,544","17,473"

In [14]:
#There's something wrong with the data

# Import Rail transport of passengers: Read the csv file as a dataframe
file_path_road_pg = r'C:\Users\猫小鱼\Desktop\TIL\Programming\final project\data\road_pg.csv'
df_road_pg = pd.read_csv(file_path_road_pg)

# Rename columns and rows
df_road_pg.columns = df_road_pg.iloc[7].tolist()
df_road_pg = df_road_pg.rename(columns={df_road_pg.columns[0]: 'GEO'})

# Clean the data by dropping columns of the dataframe that will not be used
# These rows are used to indicate the data, and columns are used to explain the accuracy of the data
df_road_pg = df_road_pg.iloc[9:37]
columns_remove = [2,4,6,8]
df_road_pg = df_road_pg.drop( df_rail_pg.columns[columns_remove], axis=1 )

# Delete the rows without data and use European region or country as the row name
#df_rail_pg = df_rail_pg.set_index('GEO')
#df_rail_pg = df_rail_pg[~(df_rail_pg == ':').all(axis=1)]

df_road_pg

,GEO,NaN,2014,NaN,NaN,2016,NaN,NaN,2018,NaN,NaN,2020,NaN,2021,NaN
9,Belgium,b,"15,215",NaN,b,"13,306",NaN,NaN,:,NaN,NaN,:,NaN,:,NaN
10,Bulgaria,NaN,"11,447.100",NaN,NaN,"12,210.200",NaN,NaN,"9,886.500",NaN,NaN,"5,037.600",NaN,"4,949.700",NaN
11,Czechia,NaN,"15,750.800",NaN,NaN,"15,841.300",NaN,NaN,"17,265",NaN,NaN,"8,593.400",NaN,"8,351.400",NaN
12,Denmark,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,:,NaN
13,Germany,NaN,"62,227",NaN,NaN,"64,073",NaN,NaN,"62,520",NaN,NaN,"34,025",NaN,"34,259",NaN
14,Estonia,NaN,"2,511",NaN,NaN,"2,938",NaN,b,"2,787",NaN,NaN,"1,557",NaN,"1,392",NaN
15,Ireland,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,:,NaN
16,Spain,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,:,NaN
17,France,NaN,"49,914",NaN,NaN,"51,307",NaN,NaN,"51,905",NaN,NaN,"33,651",NaN,"35,602.800",NaN
18,Croatia,NaN,"3,648",NaN,NaN,"3,802",NaN,NaN,"3,843",NaN,NaN,"2,076",NaN,"2,394",NaN
19,Italy,NaN,:,NaN,NaN,:,NaN,NaN,29,p,NaN,17,NaN,23,NaN
20,Latvia,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,:,NaN
21,Lithuania,NaN,"2,671.700",NaN,NaN,"2,361.200",NaN,NaN,"2,583.200",NaN,NaN,"1,486",NaN,"1,412.400",NaN
22,Hungary,NaN,"17,440.670",NaN,NaN,"17,622.878",NaN,NaN,"18,659.990",NaN,NaN,"12,424.981",NaN,"12,309.618",NaN
23,Malta,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,:,NaN
24,Austria,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,:,NaN
25,Poland,NaN,"21,449",NaN,NaN,"19,168",NaN,NaN,"16,969",NaN,NaN,"7,177",NaN,"7,448",NaN
26,Portugal,NaN,:,NaN,NaN,"7,612.120",NaN,NaN,"7,925.710",NaN,NaN,"3,939.500",NaN,"5,900.200",NaN
27,Romania,NaN,"18,339",NaN,b,"24,724",NaN,NaN,"25,856",NaN,NaN,"17,858",NaN,"18,934",NaN
28,Slovenia,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,NaN,:,z,:,z
29,Finland,NaN,"4,627",NaN,NaN,:,NaN,NaN,:,NaN,NaN,"2,589",NaN,:,NaN
30,Sweden,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,:,NaN
31,Iceland,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,:,NaN
32,Norway,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,:,NaN
33,Switzerland,NaN,"5,376",NaN,NaN,"5,609",NaN,NaN,"5,729",NaN,NaN,"4,996",NaN,"5,286",NaN
34,United Kingdom,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,:,NaN
35,North Macedonia,NaN,:,NaN,NaN,"2,068.943",NaN,NaN,"2,246.968",NaN,NaN,661.947,NaN,631.265,NaN
36,Serbia,NaN,:,NaN,NaN,:,NaN,NaN,:,NaN,NaN,"3,086",NaN,"3,586",NaN